cv <- function(h){
  #N, wt, x, y, G, yhat, yhat2, pihat, hv, coord, _dist_, seq, offset, alphai, S, Si, parg, pargg, ujg, bg, lambdag, pos0, pos1, pos02, nvar  
  if(method=="adaptiven"){
    #hv <- matrix(0,1,1)
    hv <- 0
    #yhat <- matrix(0,1,1)
    yhat <- 0
    # create &output from hv[colname='h'];
  }

%IF %UPCASE(&method)=ADAPTIVEN %THEN %DO;

do i=1 to n;
%END;
%IF %UPCASE(&method)=FIXED_G or %UPCASE(&method)=FIXED_BSQ or %UPCASE(&method)=ADAPTIVE_BSQ %THEN %DO;
do i=1 to n;
%END;
do j=1 to n;
seqi=j(n,1,i);
dist=seqi||seq`||_dist_[,i];
%IF %UPCASE(&distancekm)=YES %THEN %DO;
dist[,3]=dist[,3]*111;
%END;
end;
u=nrow(dist);
w=j(u,1,0);
do jj=1 to u;
w[jj]=exp(-0.5*(dist[jj,3]/h)**2);
%IF %UPCASE(&method)=FIXED_BSQ or %UPCASE(&method)=ADAPTIVEN %THEN %DO;
w[jj]=(1-(dist[jj,3]/h)**2)**2;
%END;
%if %UPCASE(&bandwidth)=CV %THEN %DO;w[i]=0;%END;
end;
%IF %UPCASE(&method)=FIXED_BSQ or %UPCASE(&method)=ADAPTIVEN %THEN %DO;
position=loc(dist[,3]<=h);
w[position]=0;
%END;
%IF %UPCASE(&method)=ADAPTIVE_BSQ %THEN %DO;
call sort(dist,{3});
dist=dist||(1:nrow(dist))`;
w=j(n,2,0);	
hn=dist[h,3];
do jj=1 to n;
if dist[jj,4]<=h then
w[jj,1]=(1-(dist[jj,3]/hn)**2)**2;
else w[jj,1]=0;
w[jj,2]=dist[jj,2];
end;
%if %UPCASE(&bandwidth)=CV %THEN %DO;w[loc(w[,2]=i)]=0;%END;
call sort(w,{2});
w=w[,1];
%END;

b=bg;
nj=X*b+offset;
uj=exp(nj);
par=parg;
lambda=lambdag;
njl=G*lambda;
njl=choose(njl>&maxg,&maxg,njl);
njl=choose(njl<-&maxg,-&maxg,njl);

%if %upcase(&model) ne ZIP and %upcase(&model) ne ZINB %then %do;
zk=0;
%end;
%else %do;
lambda0=(ncol(pos0)-sum((parg/(uj+parg))##parg))/n;
                        if lambda0>0 then do;
                        lambda0=log(lambda0/(1-lambda0));
                        lambda=lambda0//j(ncol(G)-1,1,0);
                        njl=G*lambda;
                        end;
                        zk=1/(1+exp(-njl)#(par/(par+uj))##par);
                              zk=choose(y>0,0,zk);
                              %end;
                              
                              dllike=1;
                              llike=0;
                              j=1;
                              do while (abs(dllike)>0.00001 & j<=600);
                              
                              ddpar=1;
                              *do while (abs(ddpar)>0.000001);
                              dpar=1;
                              parold=par;
                              aux1=1;
                              aux2=1;
                              int=1;
                              %if %upcase(&model)=ZIP or %upcase(&model)=POISSON %then %do;
                              alpha=1E-6;par=1/alpha;
                              %end;
                              %else %do;
                              if par<=1E-5 then do;if i>1 then par=1/alphai[i-1,2];end;
                              if par>=1E6 then do;
                              par=1E6;dpar=0;
                              alpha=1/par;
                              b=bg;
                              uj=exp(X*b+offset);
                              lambda=lambdag;
                              njl=G*lambda;
                              njl=choose(njl>&maxg,&maxg,njl);
                              njl=choose(njl<-&maxg,-&maxg,njl);
                              zk=1/(1+exp(-njl)#(parg/(parg+uj))##parg);
                                    zk=choose(y>0,0,zk);
                                    if any(lambda)=0 then zk=0;
                                    end;
                                    do while (abs(dpar)>0.000001 & aux2<200);
                                    par=choose(par<1E-10,1E-10,par);
                                    gf=sum(w#wt#(1-zk)#(digamma(par+y)-digamma(par)+log(par)+1-log(par+uj)-(par+y)/(par+uj)));
                                           hess=sum(w#wt#(1-zk)#(trigamma(par+y)-trigamma(par)+1/par-2/(par+uj)+(y+par)/(par+uj)##2));
                                                    hess=choose(hess=0,1E-23,hess);
                                                    par0=par;
                                                    par=par0-inv(hess)*gf;
                                                    dpar=par-par0;
                                                    if par>=1E6 then do;
                                                    par=1E6;dpar=0;
                                                    alpha=1/par;
                                                    b=bg;
                                                    uj=exp(X*b+offset);
                                                    lambda=lambdag;
                                                    njl=G*lambda;
                                                    njl=choose(njl>&maxg,&maxg,njl);
                                                    njl=choose(njl<-&maxg,-&maxg,njl);
                                                    zk=1/(1+exp(-njl)#(parg/(parg+uj))##parg);
                                                          zk=choose(y>0,0,zk);
                                                          if any(lambda)=0 then zk=0;
                                                          end;
                                                          aux2=aux2+1;
                                                          end;
                                                          if par<=1E-5 then do;
                                                          par=1E6;
                                                          b=bg;
                                                          uj=exp(X*b+offset);
                                                          lambda=lambdag;
                                                          njl=G*lambda;
                                                          njl=choose(njl>&maxg,&maxg,njl);
                                                          njl=choose(njl<-&maxg,-&maxg,njl);
                                                          zk=1/(1+exp(-njl)#(parg/(parg+uj))##parg);
                                                                zk=choose(y>0,0,zk);
                                                                if any(lambda)=0 then zk=0;
                                                                end;
                                                                alpha=1/par;
                                                                *print i j b lambda par alpha aux2;
                                                                %end;
                                                                
                                                                dev=0;
                                                                ddev=1;
                                                                nj=x*b+offset;
                                                                nj=choose(nj>700,700,nj);
                                                                nj=choose(nj<-700,-700,nj);
                                                                uj=exp(nj);
                                                                do while (abs(ddev)>0.000001 & aux1<100);
                                                                uj=choose(uj>1E100,1E100,uj);
                                                                Ai=(1-zk)#((uj/(1+alpha*uj)+(y-uj)#(alpha*uj/(1+2*alpha*uj+alpha**2*uj##2))));
                                                                Ai=choose(Ai<=0,1E-5,Ai);
                                                                uj=choose(uj<1E-150,1E-150,uj);
                                                                denz=(((uj/(1+alpha*uj)+(y-uj)#(alpha*uj/(1+2*alpha*uj+alpha**2*uj##2))))#(1+alpha*uj));
                                                                        denz=choose(denz=0,1E-5,denz);
                                                                        zj=(nj+(y-uj)/denz)-offset;
                                                                        if det(x`*(w#Ai#x#wt))=0 then b=j(nvar,1,0);
                                                                                   else b=inv(x`*(w#Ai#x#wt))*x`*(w#Ai#wt#zj);
                                                                                                                  nj=x*b+offset;
                                                                                                                  nj=choose(nj>700,700,nj);
                                                                                                                  nj=choose(nj<-700,-700,nj);
                                                                                                                  uj=exp(nj);
                                                                                                                  olddev=dev;
                                                                                                                  uj=choose(uj>1E10,1E10,uj);
                                                                                                                  uj=choose(uj=0,1E-10,uj);
                                                                                                                  if par=1E6 then gamma1=/*(gamma(par+y)/(gamma(y+1)#gamma(par)))#*/(uj/(uj+par))##y#exp(-uj);
                                                                                                                                                          else gamma1=/*(gamma(par+y)/(gamma(y+1)#gamma(par)))#*/(uj/(uj+par))##y#(par/(uj+par))##par;
                                                                                                                                                                                       gamma1=choose(gamma1<=0,1E-10,gamma1);
                                                                                                                                                                                       dev=sum((1-zk)#(log(gamma1)));
                                                                                                                                                                                               ddev=dev-olddev;
                                                                                                                                                                                               *print b par aux1 dev olddev ddev;
                                                                                                                                                                                               aux1=aux1+1;
                                                                                                                                                                                               end;
                                                                                                                                                                                               ddpar=par-parold;
                                                                                                                                                                                               *end;
                                                                                                                                                                                               
                                                                                                                                                                                               %if %upcase(&model)=ZIP or %upcase(&model)=ZINB %then %do;
                                                                                                                                                                                               
                                                                                                                                                                                               if j=1 then do;alphatemp=alpha;lambdatemp=lambda[1];end;
                                                                                                                                                                                               else do;alphatemp=alphatemp//alpha;lambdatemp=lambdatemp//lambda[1];end;
                                                                                                                                                                                               alphatemp=round(alphatemp,0.0000001);
                                                                                                                                                                                               lambdatemp=round(lambdatemp,0.0000001);
                                                                                                                                                                                               *print i j alphatemp (nrow(alphatemp)) (ncol(unique(alphatemp)));
                                                                                                                                                                                               %if %upcase(&model)=ZINB %then %do;
                                                                                                                                                                                               if j>300 & nrow(alphatemp)>ncol(unique(alphatemp)) & 
                                                                                                                                                                                                 nrow(lambdatemp)>ncol(unique(lambdatemp))then do;
                                                                                                                                                                                               %end;
                                                                                                                                                                                               %if %upcase(&model)=ZIP %then %do;
                                                                                                                                                                                               *print i j lambdatemp (nrow(lambdatemp)) (ncol(unique(lambdatemp)));
                                                                                                                                                                                               if j>300 & nrow(lambdatemp)>ncol(unique(lambdatemp))then do;
                                                                                                                                                                                               %end;
                                                                                                                                                                                               lambda=j(ncol(G),1,0);
                                                                                                                                                                                               njl=G*lambda;
                                                                                                                                                                                               zk=j(n,1,0);
                                                                                                                                                                                               end;
                                                                                                                                                                                               else do;
                                                                                                                                                                                               
                                                                                                                                                                                               aux3=1;
                                                                                                                                                                                               dev=0;
                                                                                                                                                                                               ddev=1;
                                                                                                                                                                                               njl=G*lambda;
                                                                                                                                                                                               njl=choose(njl>&maxg,&maxg,njl);
                                                                                                                                                                                               njl=choose(njl<-&maxg,-&maxg,njl);
                                                                                                                                                                                               pi=exp(njl)/(1+exp(njl));
                                                                                                                                                                                               do while (abs(ddev)>0.000001 & aux3<100);
                                                                                                                                                                                               Aii=pi#(1-pi);
                                                                                                                                                                                               Aii=choose(Aii<=0,1E-5,Aii);	
                                                                                                                                                                                               zj=njl+(zk-pi)/Aii;
                                                                                                                                                                                               if det((G#Aii#w#wt)`*G)=0 then lambda=j(ncol(G),1,0);
                                                                                                                                                                                                       else lambda=inv((G#Aii#w#wt)`*G)*(G#Aii#w#wt)`*zj;
                                                                                                                                                                                                                        njl=G*lambda;
                                                                                                                                                                                                                        njl=choose(njl>&maxg,&maxg,njl);
                                                                                                                                                                                                                        njl=choose(njl<-&maxg,-&maxg,njl);
                                                                                                                                                                                                                        pi=exp(njl)/(1+exp(njl));
                                                                                                                                                                                                                        olddev=dev;
                                                                                                                                                                                                                        dev=sum(zk#njl-log(1+exp(njl)));
                                                                                                                                                                                                                                ddev=dev-olddev;
                                                                                                                                                                                                                                *print lambda aux3 dev olddev ddev;
                                                                                                                                                                                                                                aux3=aux3+1;
                                                                                                                                                                                                                                end;
                                                                                                                                                                                                                                
                                                                                                                                                                                                                                end;
                                                                                                                                                                                                                                %end;
                                                                                                                                                                                                                                
                                                                                                                                                                                                                                njl=G*lambda;
                                                                                                                                                                                                                                njl=choose(njl>&maxg,&maxg,njl);
                                                                                                                                                                                                                                njl=choose(njl<-&maxg,-&maxg,njl);
                                                                                                                                                                                                                                zk=1/(1+exp(-njl)#(par/(par+uj))##par);
                                                                                                                                                                                                                                      zk=choose(y>0,0,zk);
                                                                                                                                                                                                                                      if any(lambda)=0 then zk=j(n,1,0);
                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                      %if %upcase(&model) ne ZIP and %upcase(&model) ne ZINB %then %do;
                                                                                                                                                                                                                                      zk=0;
                                                                                                                                                                                                                                      %end;
                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                      oldllike=llike;
                                                                                                                                                                                                                                      llike=sum(zk#(njl)-log(1+exp(njl))+(1-zk)#(log(gamma1)));
                                                                                                                                                                                                                                                dllike=llike-oldllike;
                                                                                                                                                                                                                                                *print i j b alpha lambda llike dllike;
                                                                                                                                                                                                                                                j=j+1;
                                                                                                                                                                                                                                                end;
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                %IF %UPCASE(&method)=FIXED_G or %UPCASE(&method)=FIXED_BSQ or %UPCASE(&method)=ADAPTIVE_BSQ %THEN %DO;
                                                                                                                                                                                                                                                yhat[i]=uj[i];
                                                                                                                                                                                                                                                pihat[i]=njl[i];
                                                                                                                                                                                                                                                alphai[i]= alpha;
                                                                                                                                                                                                                                                if det(x`*(w#Ai#x#wt))=0 then S[i]=0;
                                                                                                                                                                                                                                                           else S[i]= (x[i,]*inv(x`*(w#Ai#x#wt))*(x#w#Ai#wt)`)[i];
                                                                                                                                                                                                                                                                       %if %upcase(&model)=ZIP or %upcase(&model)=ZINB %then %do;
                                                                                                                                                                                                                                                                       yhat[i]=(uj#(1-exp(njl)/(1+exp(njl))))[i];
                                                                                                                                                                                                                                                                                yhat2[i]=uj[i];
                                                                                                                                                                                                                                                                                if det(G`*(w#Aii#G#wt))=0 then Si[i]=0;
                                                                                                                                                                                                                                                                                           else Si[i]= (G[i,]*inv(G`*(w#Aii#G#wt))*(G#w#Aii#wt)`)[i];
                                                                                                                                                                                                                                                                                                        if any(lambda)=0 then Si[i]=0;
                                                                                                                                                                                                                                                                                                        %end;
                                                                                                                                                                                                                                                                                                        end;
                                                                                                                                                                                                                                                                                                        CV=((y-yhat)#wt)`*(y-yhat);
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            _par_=1/alphai;
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            %IF %UPCASE(&model)=ZINB or %UPCASE(&model)=ZIP %THEN %DO;
                                                                                                                                                                                                                                                                                                            if any(lambda)=0 then do;
                                                                                                                                                                                                                                                                                                            ll=sum(-log(0+exp(pihat[pos0]))+log(0*exp(pihat[pos0])+(_par_[pos0]/(_par_[pos0]+yhat2[pos0]))##_par_[pos0]))+
                                                                                                                                                                                                                                                                                                                                                sum(-log(0+exp(pihat[pos1]))+lgamma(_par_[pos1]+y[pos1,])-lgamma(y[pos1,]+1)-lgamma(_par_[pos1])+
                                                                                                                                                                                                                                                                                                                                                      y[pos1]#log(yhat2[pos1]/(_par_[pos1]+yhat2[pos1]))+_par_[pos1]#log(_par_[pos1]/(_par_[pos1]+yhat2[pos1])));
                                                                                                                                                                                                                                                                                                                                                    llnull1=sum(-log(1+zk[pos0])+log(zk[pos0]+(_par_[pos0]/(_par_[pos0]+y[pos0,]))##_par_[pos0]))+
                                                                                                                                                                                                                                                                                                                                                                                     sum(-log(1+zk[pos1])+lgamma(_par_[pos1]+y[pos1,])-lgamma(y[pos1,]+1)-lgamma(_par_[pos1])+
                                                                                                                                                                                                                                                                                                                                                                                           y[pos1]#log(y[pos1,]/(_par_[pos1]+y[pos1,]))+_par_[pos1]#log(_par_[pos1]/(_par_[pos1]+y[pos1,])));
                                                                                                                                                                                                                                                                                                                                                                                         llnull2=sum(-log(1+0)+log(0+(_par_/(_par_+y[:]))##_par_))+
                                                                                                                                                                                                                                                                                                                                                                                                                   sum(-log(1+0)+lgamma(_par_+y)-lgamma(y+1)-lgamma(_par_)+
                                                                                                                                                                                                                                                                                                                                                                                                                         y#log(y[:]/(_par_+y[:]))+_par_#log(_par_/(_par_+y[:])));
                                                                                                                                                                                                                                                                                                                                                                                                                       end;
                                                                                                                                                                                                                                                                                                                                                                                                                       else do;
                                                                                                                                                                                                                                                                                                                                                                                                                       ll=sum(-log(1+exp(pihat[pos0]))+log(exp(pihat[pos0])+(_par_[pos0]/(_par_[pos0]+yhat2[pos0]))##_par_[pos0]))+
                                                                                                                                                                                                                                                                                                                                                                                                                                                           sum(-log(1+exp(pihat[pos1]))+lgamma(_par_[pos1]+y[pos1])-lgamma(y[pos1]+1)-lgamma(_par_[pos1])+
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 y[pos1]#log(yhat2[pos1]/(_par_[pos1]+yhat2[pos1]))+_par_[pos1]#log(_par_[pos1]/(_par_[pos1]+yhat2[pos1])));
                                                                                                                                                                                                                                                                                                                                                                                                                                                               llnull1=sum(-log(1+zk[pos0])+log(zk[pos0]+(_par_[pos0]/(_par_[pos0]+y[pos0]))##_par_[pos0]))+
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                sum(-log(1+zk[pos1])+lgamma(_par_[pos1]+y[pos1])-lgamma(y[pos1]+1)-lgamma(_par_[pos1])+
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      y[pos1]#log(y[pos1]/(_par_[pos1]+y[pos1]))+_par_[pos1]#log(_par_[pos1]/(_par_[pos1]+y[pos1])));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    end;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    dev=2*(llnull1-ll);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    npar=sum(S)+sum(Si);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    AIC=2*npar-2*ll;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    AICc=AIC+2*(npar*(npar+1)/(n-npar-1));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    %IF %UPCASE(&model)=ZINB %THEN %DO;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    AIC=2*(npar+npar/(ncol(x)+ncol(G)))-2*ll;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    AICc=AIC+2*((npar+npar/(ncol(x)+ncol(G)))*((npar+npar/(ncol(x)+ncol(G)))+1)/(n-(npar+npar/(ncol(x)+ncol(G)))-1));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    %END;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    %END;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    %IF %UPCASE(&model)=POISSON or %UPCASE(&model)=NEGBIN %THEN %DO;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if ncol(pos02)=0 then do;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    pos0=pos1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    pos0x=1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    pos0xl=1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    end;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else do;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    pos0x=(_par_[pos0]/(_par_[pos0]+yhat[pos0]))##_par_[pos0];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    pos0xl=(_par_[pos0]/(_par_[pos0]+y[pos0,]))##_par_[pos0];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    end;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ll=sum(-log(0+exp(pihat[pos0]))+log(0*exp(pihat[pos0])+pos0x))+
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      sum(-log(0+exp(pihat[pos1]))+lgamma(_par_[pos1]+y[pos1,])-lgamma(y[pos1,]+1)-lgamma(_par_[pos1])+
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            y[pos1]#log(yhat[pos1]/(_par_[pos1]+yhat[pos1]))+
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          _par_[pos1]#log(_par_[pos1]/(_par_[pos1]+yhat[pos1])));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          llnull1=sum(-log(1+zk)+log(zk+pos0xl))+
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            sum(-log(1+zk)+lgamma(_par_[pos1]+y[pos1,])-lgamma(y[pos1,]+1)-lgamma(_par_[pos1])+
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  y[pos1]#log(y[pos1,]/(_par_[pos1]+y[pos1,]))+_par_[pos1]#log(_par_[pos1]/(_par_[pos1]+y[pos1,])));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                dev=2*(llnull1-ll);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                npar=sum(S);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                AIC=2*npar-2*ll;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                AICc=AIC+2*(npar*(npar+1)/(n-npar-1));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                %IF %UPCASE(&model)=NEGBIN %THEN %DO;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                AIC=2*(npar+npar/ncol(x))-2*ll;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                AICc=AIC+2*(npar+npar/ncol(x))*(npar+npar/ncol(x)+1)/(n-(npar+npar/ncol(x))-1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                %END;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                %END;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                %if %UPCASE(&bandwidth)=AIC %THEN %DO;CV=AICC;%END;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                %END;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                %ELSE %IF %UPCASE(&method)=ADAPTIVEN %THEN %DO;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                yhat[1]=x[i,]*b;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                CV=((y[i]-yhat)#wt)`*(y[i]-yhat);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    %END;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    free dist w;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    res=cv||npar;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return (res);
}